### PR TITLE
Added underscore to private methods and attributes

### PR DESCRIPTION
**Pull request by aswinm**

### CODE REVIEW

**Comment by bravegnu** [comment]
@aswinm, will wait for @hrishikeshsathe to submit his changes for #19.

**Comment by bravegnu** [comment]
@aswinmn, can you please rebase your change.

**Comment by aswinm** [comment]
@bravegnu ya sure...

**Comment by aswinm** [comment]
@bravegnu Edited the code..

**Comment by bravegnu** [comment]
I am not very sure how this works. But I guess you have to send in a separate pull request.

**Pull request merged**
