### PR TITLE
Docstrings added to functions

### PR DESCRIPTION
**Pull request by aswinm**

### CODE REVIEW

**Comment by aswinm** [comment]
@hrishikeshsathe: The changes have been made :)

**Comment by hrishikeshsathe** [comment]
:+1:
All set!

**Comment by aswinm** [comment]
@hrishikeshsathe Thank you :+1:

**Comment by bravegnu** [comment]
The "This function" prefix in every docstring is superfluous. Can we remove it?

**Comment by bravegnu** [comment]
Also if the comment is long than *one line*, it should be split into one line short descrption a blank line and multine long description.

**Comment by bravegnu** [comment]
For public methods, please follow the Google docstring convention, available at http://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Comments#Comments

In our case the constructor and run() methods are public.

**Comment by aswinm** [comment]
@bravegnu Is the current one ok?

**Comment by aswinm** [comment]
@bravegnu I Have modified that too.. :+1:

**Comment by aswinm** [comment]
@bravegnu Made those fixes too :+1:

**Comment by bravegnu** [comment]
Good work, Aswin. One last request, can you squash all commits into one commit? I think you need to send in a separate pull request, I am not sure though.

**Comment by aswinm** [comment]
@bravegnu I think merging this pull request actually updates the entire changes made

@shrayasr will do that from next time

**Comment by shrayasr** [comment]
@aswinm it will add 7 + 1 commits to the main repository. What @bravegnu is asking you to do is to squash those 7 commits into one since they're all part of the same changeset. Read more about squashing git commits [here](http://davidwalsh.name/squash-commits-git) and [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by aswinm** [comment]
@shrayasr got it :+1:

**Comment by shrayasr** [comment]
:)

**Comment by bravegnu** [comment]
Your changes are in, thanks!

**Pull request closed without merging**
